<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CoachSearch;
use AppBundle\Form\CoachSearchType;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;

/**
 * CoachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllCoach(CoachSearch $search){
        $query = $this->findAllQuery();

        if($search ->getPrice()){
            $query = $query
                ->where('c.price <= :price')
                ->setParameter('price', $search->getPrice());
        }
            return $query->getQuery()->getResult();
    }



    private function findAllQuery(){

        return $this->createQueryBuilder('c');
    }
}
