<?php

namespace AppBundle\Repository;


/**
 * CoachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoachRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByFilters($searchPrice = null, $searchSport = null)
    {
        $qb = $this->createQueryBuilder('c');

        if($searchPrice != null)
        {
            $qb->andWhere('c.price <= :price')
                ->setParameter('price', $searchPrice);
        }
        if($searchSport  != null)
        {
            $qb->andWhere('c.sport = :sport')
                ->setParameter('sport', $searchSport);
        }

        return $qb->getQuery()->getResult();
    }
}